name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: psf/black@stable

      # - name: Set up Python
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.8

      # - name: Install Python dependencies
      #   run: pip install black

      # - name: Run linters
      #   uses: wearerequired/lint-action@v2
      #   with:
      #     black: true
